name: Secrets Manager
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    container: python:3.11.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: flake8 .

  build:
    runs-on: ubuntu-18.04
    container: python:3.11.2
    needs: [test]

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup distribution package
        run: python setup.py sdist
